# Generated by Django 4.2.10 on 2024-04-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lms_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='badge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
