# Generated by Django 4.2.10 on 2024-04-27 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Lms_App', '0003_submenu_alter_app_menu_delete_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('external', models.BooleanField(default=False)),
                ('target', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='badge',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='badge_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='badge_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Lms_App.menuitem'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='permission',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='target',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='users',
            field=models.ManyToManyField(related_name='apps', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='SubMenu',
        ),
        migrations.AddField(
            model_name='submenuitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenu', to='Lms_App.menuitem'),
        ),
    ]
