# Generated by Django 4.2.10 on 2024-04-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lms_App', '0004_submenuitem_remove_menuitem_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenuitem',
            name='badge_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='submenuitem',
            name='badge_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
