# Generated by Django 4.2.10 on 2024-04-27 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lms_App', '0005_submenuitem_badge_color_submenuitem_badge_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='SubMenuItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lms_App.submenuitem'),
        ),
        migrations.AlterField(
            model_name='app',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Lms_App.menuitem'),
        ),
    ]
