# Generated by Django 4.2.10 on 2024-04-29 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lms_App', '0006_app_submenuitem_alter_app_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='badge_count',
            new_name='badge',
        ),
    ]
