# Generated by Django 4.2.10 on 2024-05-07 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lms_App', '0009_rename_badge_menuitem_badge_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submenuitem',
            old_name='menu_item',
            new_name='menu',
        ),
    ]
