# Generated by Django 4.2.10 on 2024-05-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lms_App', '0010_rename_menu_item_submenuitem_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
